package com.Chitkara.dto;

import com.Chitkara.enums.Gender;
import java.time.LocalDate;

public class EmployeeDTO {
    private int employeeId; // Auto-generated by DB
    private String firstName;
    private String lastName;
    private Gender gender;
    private String city;
    private String state;
    private String mobileNumber;
    private String emailId;
    private LocalDate employeeBirthDate;
    private double salary;

    // Getters and Setters
    public int getEmployeeId() { return employeeId; }
    public void setEmployeeId(int employeeId) { this.employeeId = employeeId; }
    public String getFirstName() { return firstName; }
    public void setFirstName(String firstName) { this.firstName = firstName; }
    public String getLastName() { return lastName; }
    public void setLastName(String lastName) { this.lastName = lastName; }
    public Gender getGender() { return gender; }
    public void setGender(Gender gender) { this.gender = gender; }
    public String getCity() { return city; }
    public void setCity(String city) { this.city = city; }
    public String getState() { return state; }
    public void setState(String state) { this.state = state; }
    public String getMobileNumber() { return mobileNumber; }
    public void setMobileNumber(String mobileNumber) { this.mobileNumber = mobileNumber; }
    public String getEmailId() { return emailId; }
    public void setEmailId(String emailId) { this.emailId = emailId; }
    public LocalDate getEmployeeBirthDate() { return employeeBirthDate; }
    public void setEmployeeBirthDate(LocalDate employeeBirthDate) { this.employeeBirthDate = employeeBirthDate; }
    public double getSalary() { return salary; }
    public void setSalary(double salary) { this.salary = salary; }

    @Override
    public String toString() {
        return  "\n{"+
                "\nemployeeId: " + employeeId +
                "\nfirstName: '" + firstName + '\'' +
                "\nlastName: '" + lastName + '\'' +
                "\ngender: " + gender +
                "\ncity: '" + city + '\'' +
                "\nstate: '" + state + '\'' +
                "\nmobileNumber: '" + mobileNumber + '\'' +
                "\nemailId: '" + emailId + '\'' +
                "\nemployeeBirthDate: " + employeeBirthDate +
                "\nsalary: " + salary +
                "\n}";
    }
}